### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by Qwarctick** [VirginiaSabando/ChemVA#1]
Hello,

Your `server.py` file have some python requirements. Can you provide a requirements.txt file please ? Or at minimum the list of packages with versions number. It helps a lot to install your tool. You can generate it with `pip freeze > requirements.txt` if you use pip to manage your dependencies.

**Comment by VirSabando** [comment]
Hello, thank you for pointing this out!

I have just uploaded a file named 'chemva.yml' that will enable you to clone the Conda env onto which the backend server is running. You can find such file within the folder named 'ChemVA_backend'.
Please let us know if this solves your issue :-)

**Comment by Qwarctick** [comment]
Nice thank you. After seeing the list of requirements, the file is welcome.
